import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { Check, ChevronDown, Copy, Search, ExternalLink, MoreHorizontal } from 'lucide-react';
import { ShowcaseLayout, PageHeading } from '../showcase/layout';
import { Button } from '../design-system/components/button';
import { ButtonLink } from '../design-system/components/button-link';
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuCheckboxItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuSub, DropdownMenuSubTrigger, DropdownMenuSubContent } from '../design-system/components/dropdown-menu';
import { Input } from '../design-system/components/input';
import { Badge } from '../design-system/components/badge';
import { Card } from '../design-system/components/card';
import { Switch } from '../design-system/components/switch';
import { Textarea } from '../design-system/components/textarea';
import { MotionComponents } from '../showcase/motion-components';
import { MenuComponents } from '../showcase/menu-components';
export const Route = createFileRoute('/components')({ head: () => ({ meta: [{ title: 'Components — Refined Modern Tech' }, { name: 'description', content: 'Interactive previews of every Refined Modern Tech component and its variants.' }, { property: 'og:title', content: 'Components — Refined Modern Tech' }, { property: 'og:description', content: 'Explore buttons, button-style links, dropdown menus, and form controls in context.' }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary' }] }), component: Components });
const names = ['Button', 'Button link', 'Dropdown menu', 'Select', 'Multi-select', 'Checkbox', 'Table', 'Toggle group', 'Nav menu', 'Choice dialog', 'Lightbox', 'Input', 'Badge', 'Card', 'Switch', 'Textarea', 'Sheet', 'Dialog', 'Accordion', 'Collapsible', 'Popover', 'Tooltip', 'Tabs', 'Toast', 'Skeleton', 'Progress'];
function Example({ code }: { code: string }) { const [copied, setCopied] = useState(false); return <details className="group mt-6 border-t border-border pt-4"><summary className="flex cursor-pointer list-none items-center gap-2 text-xs font-medium text-muted-foreground hover:text-foreground">View code <ChevronDown className="size-3 transition-transform group-open:rotate-180" /></summary><div className="relative mt-4"><pre className="overflow-x-auto rounded-md bg-muted p-4 pr-12 font-mono text-xs leading-relaxed text-foreground"><code>{code}</code></pre><Button size="icon" variant="ghost" className="absolute right-2 top-2" aria-label="Copy example" onClick={async () => { await navigator.clipboard.writeText(code); setCopied(true); setTimeout(() => setCopied(false), 2000); }}>{copied ? <Check className="size-4" /> : <Copy className="size-4" />}</Button></div></details>; }
function Section({ name, description, children, code }: { name: string; description: string; children: React.ReactNode; code: string }) { return <section id={name.toLowerCase().replaceAll(' ', '-')} className="scroll-mt-28 border-t border-border py-10"><div className="mb-7"><p className="text-xs font-medium text-primary">@refined/{name.toLowerCase().replaceAll(' ', '-')}</p><h2 className="mt-2 font-display text-2xl font-semibold">{name}</h2><p className="mt-2 text-sm text-muted-foreground">{description}</p></div>{children}<Example code={code} /></section>; }
function Specimen({ label, children }: { label: string; children: React.ReactNode }) { return <div className="flex min-h-24 flex-col justify-between gap-4 rounded-md border border-border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><div className="flex min-h-10 items-center">{children}</div></div>; }
function Components() { const [query, setQuery] = useState(''); const [enabled, setEnabled] = useState(true); const [updates, setUpdates] = useState(false); const [project, setProject] = useState(''); const [notes, setNotes] = useState(''); const [message, setMessage] = useState(''); const [menuMessage, setMenuMessage] = useState(''); const [compact, setCompact] = useState(false); return <ShowcaseLayout><PageHeading eyebrow="Library / 03" title="The working parts." description="A focused set of controls for the moments that matter. Try them, switch palettes, and see the system hold together." /><div className="grid min-w-0 grid-cols-[minmax(0,1fr)] gap-12 lg:grid-cols-[208px_minmax(0,1fr)] lg:gap-16"><aside className="min-w-0 lg:sticky lg:top-28 lg:self-start"><label htmlFor="component-search" className="text-xs font-semibold uppercase text-muted-foreground">Components · {names.length}</label><div className="relative mt-3 min-w-0"><Search className="pointer-events-none absolute left-3 top-3 size-4 text-muted-foreground" /><Input id="component-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Find a component" className="pl-9" /></div><nav aria-label="Components" className="mt-4 flex max-w-full gap-1 overflow-x-auto lg:flex-col">{names.filter(n => n.toLowerCase().includes(query.toLowerCase())).map(name => <a key={name} href={`#${name.toLowerCase().replaceAll(' ', '-')}`} className="shrink-0 rounded-md px-3 py-2 text-sm text-muted-foreground hover:bg-muted hover:text-foreground">{name}</a>)}</nav></aside><div className="min-w-0">
<Section name="Button" description="Clear actions with a consistent size and emphasis scale." code={'import { Button } from "@/design-system/refined-modern-tech";\n<Button variant="primary" size="md">Create project</Button>'}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{(['primary','secondary','outline','ghost','destructive'] as const).map(v => <Specimen key={v} label={v}><Button variant={v}>{v === 'destructive' ? 'Delete project' : v === 'ghost' ? 'View details' : 'Create project'}</Button></Specimen>)}<Specimen label="disabled"><Button disabled>Create project</Button></Specimen><Specimen label="loading"><Button loading>Saving changes</Button></Specimen><Specimen label="small / medium / large"><div className="flex flex-wrap items-center gap-2"><Button size="sm">Small</Button><Button size="md">Medium</Button><Button size="lg">Large</Button></div></Specimen></div></Section>
<Section name="Button link" description="Navigation with the same emphasis and sizing as a button." code={'import { ButtonLink } from "@/design-system/refined-modern-tech";\n<ButtonLink href="/projects" variant="outline">View projects</ButtonLink>'}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Specimen label="primary"><ButtonLink href="/colors">Explore colors <ExternalLink className="size-4" /></ButtonLink></Specimen><Specimen label="outline"><ButtonLink href="/typography" variant="outline">View typography</ButtonLink></Specimen><Specimen label="secondary"><ButtonLink href="/components" variant="secondary" size="sm">Browse components</ButtonLink></Specimen><Specimen label="ghost"><ButtonLink href="/" variant="ghost">Back to overview</ButtonLink></Specimen></div></Section>
<Section name="Dropdown menu" description="Grouped actions and settings in a keyboard-friendly menu." code={'import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, Button } from "@/design-system/refined-modern-tech";\n<DropdownMenu>\n  <DropdownMenuTrigger asChild><Button variant="outline">Options</Button></DropdownMenuTrigger>\n  <DropdownMenuContent align="start">\n    <DropdownMenuItem onSelect={() => console.log("Edit")}>Edit project</DropdownMenuItem>\n  </DropdownMenuContent>\n</DropdownMenu>'}><div className="flex flex-wrap items-center gap-4"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline">Project options <ChevronDown className="size-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="start"><DropdownMenuLabel>Project</DropdownMenuLabel><DropdownMenuItem onSelect={() => setMenuMessage('Project opened')}>Open project</DropdownMenuItem><DropdownMenuItem onSelect={() => setMenuMessage('Project duplicated')}>Duplicate</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuCheckboxItem checked={compact} onCheckedChange={setCompact}>Compact view</DropdownMenuCheckboxItem><DropdownMenuSub><DropdownMenuSubTrigger>Share</DropdownMenuSubTrigger><DropdownMenuSubContent><DropdownMenuItem onSelect={() => setMenuMessage('Link copied')}>Copy link</DropdownMenuItem><DropdownMenuItem onSelect={() => setMenuMessage('Invitation sent')}>Invite teammate</DropdownMenuItem></DropdownMenuSubContent></DropdownMenuSub><DropdownMenuSeparator /><DropdownMenuItem destructive onSelect={() => setMenuMessage('Archive selected')}>Archive project</DropdownMenuItem></DropdownMenuContent></DropdownMenu><DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="ghost" aria-label="More actions"><MoreHorizontal className="size-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="start"><DropdownMenuItem onSelect={() => setMenuMessage('Details selected')}>View details</DropdownMenuItem><DropdownMenuItem disabled>Unavailable action</DropdownMenuItem></DropdownMenuContent></DropdownMenu><span role="status" className="text-sm text-muted-foreground">{menuMessage || (compact ? 'Compact view on' : '')}</span></div></Section>
<Section name="Input" description="Reliable text entry with clear focus, disabled, and error states." code={'import { Input } from "@/design-system/refined-modern-tech";\n<label htmlFor="email">Email address</label>\n<Input id="email" type="email" placeholder="alex@northstar.co" />'}><div className="grid gap-3 sm:grid-cols-2"><Specimen label="default"><Input aria-label="Email address" type="email" placeholder="alex@northstar.co" /></Specimen><Specimen label="filled"><Input aria-label="Project name" defaultValue="Northstar Studio" /></Specimen><Specimen label="error"><div className="w-full"><Input aria-label="Invalid email" invalid defaultValue="alex@" /><p className="mt-2 text-xs text-destructive">Enter a valid email address.</p></div></Specimen><Specimen label="disabled"><Input aria-label="Disabled input" placeholder="Not available" disabled /></Specimen></div></Section>
<Section name="Badge" description="Compact labels for state, category, and emphasis." code={'import { Badge } from "@/design-system/refined-modern-tech";\n<Badge variant="accent">In review</Badge>'}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{(['primary','secondary','outline','accent','destructive'] as const).map((v,i) => <Specimen key={v} label={v}><Badge variant={v}>{['New','Draft','Archived','In review','Urgent'][i]}</Badge></Specimen>)}</div></Section>
<Section name="Card" description="A deliberate surface for grouped content, without unnecessary nesting." code={'import { Card } from "@/design-system/refined-modern-tech";\n<Card variant="default" size="md">Project summary</Card>'}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{(['default','flat','accent'] as const).map(v => <Card key={v} variant={v} className="min-h-40"><p className="text-xs text-muted-foreground">{v} / medium</p><h3 className="mt-5 font-display text-lg font-semibold">Q3 Planning</h3><p className="mt-1 text-sm text-muted-foreground">12 tasks · Updated today</p></Card>)}</div></Section>
<Section name="Switch" description="Binary settings with a visible state and native keyboard control." code={'import { Switch } from "@/design-system/refined-modern-tech";\n<label htmlFor="alerts">Email alerts</label>\n<Switch id="alerts" defaultChecked />'}><div className="grid gap-3 sm:grid-cols-2"><Specimen label="on / medium"><label className="flex w-full items-center justify-between gap-3 text-sm" htmlFor="showcase-enabled">Activity digest <Switch id="showcase-enabled" checked={enabled} onChange={e => setEnabled(e.target.checked)} /></label></Specimen><Specimen label="off / medium"><label className="flex w-full items-center justify-between gap-3 text-sm" htmlFor="showcase-updates">Product updates <Switch id="showcase-updates" checked={updates} onChange={e => setUpdates(e.target.checked)} /></label></Specimen><Specimen label="small"><label className="flex w-full items-center justify-between gap-3 text-sm" htmlFor="showcase-small">Weekly recap <Switch id="showcase-small" size="sm" defaultChecked /></label></Specimen><Specimen label="disabled"><label className="flex w-full items-center justify-between gap-3 text-sm text-muted-foreground" htmlFor="showcase-disabled">Managed by organization <Switch id="showcase-disabled" disabled checked /></label></Specimen></div></Section>
<Section name="Textarea" description="Room for longer thoughts, with matching entry states." code={'import { Textarea } from "@/design-system/refined-modern-tech";\n<label htmlFor="notes">Project notes</label>\n<Textarea id="notes" placeholder="What should the team know?" />'}><div className="grid gap-3 sm:grid-cols-2"><Specimen label="default"><Textarea aria-label="Project notes" placeholder="What should the team know?" value={notes} onChange={e => setNotes(e.target.value)} /></Specimen><Specimen label="error"><div className="w-full"><Textarea aria-label="Required description" invalid placeholder="Add a description" /><p className="mt-2 text-xs text-destructive">A description is required.</p></div></Specimen><Specimen label="disabled"><Textarea aria-label="Disabled notes" disabled placeholder="Notes are locked" /></Specimen></div></Section>
      <MenuComponents />
      <MotionComponents />
<section className="border-t border-border py-10"><p className="text-xs font-medium text-primary">COMPOSED EXAMPLE</p><h2 className="mt-2 font-display text-2xl font-semibold">A project, from the ground up.</h2><form className="mt-7 max-w-lg space-y-5" onSubmit={e => { e.preventDefault(); if (project.trim()) setMessage(`“${project.trim()}” is ready to create.`); }}><div><label htmlFor="project-title" className="mb-2 block text-sm font-medium">Project name</label><Input id="project-title" required value={project} onChange={e => setProject(e.target.value)} placeholder="e.g. Brand refresh" /></div><div><label htmlFor="project-details" className="mb-2 block text-sm font-medium">Project brief</label><Textarea id="project-details" placeholder="What is the team setting out to do?" /></div><label htmlFor="project-notify" className="flex items-center justify-between gap-4 text-sm">Notify the team when it's ready <Switch id="project-notify" defaultChecked /></label><div className="flex items-center justify-between gap-3 border-t border-border pt-5"><Badge variant="accent">New workspace</Badge><Button type="submit">Create project</Button></div>{message && <p role="status" className="text-sm text-primary">{message}</p>}</form></section>
</div></div></ShowcaseLayout>; }
